@startuml
class Member{}
class BoardMember{}
class Event{}
class Conference{}
class BoardMeeting{}
class Location{}
class Person{}
Event <|-- Conference
Event <|-- BoardMeeting

Person <|-- Member
Member <|-- BoardMember

class AAUOC{}
AAUOC o-- Person
AAUOC o-- Event
AAUOC o-- Location
Person -- Conference
Location -- Event
Event -- Member
BoardMeeting -- BoardMember
@enduml